public enum EventTypes {
    SHIP_ADDED,
    SHIP_EDITED,
    SHIP_REMOVED,
    RESOURCE_ADDED,
    RESOURCE_EDITED,
    RESOURCE_REMOVED,
    SOLUTION_ADDED,
    SOLVE,
    SAVE,
    LOAD,
    EXIT
}
