/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project.GUI;

import project.Solution;
import project.Trip;
import project.Turn;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 * @author fcastillo
 */
public class SolutionGui extends javax.swing.JPanel {

    private ToolGUI parentFrame;

    /**
     * Creates new form SolutionGUI
     */
    public SolutionGui(ToolGUI parentFrame) {
        initComponents();
        this.parentFrame = parentFrame;
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSolution = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnBack.setFont(new Font("Tahoma", Font.BOLD, 14));

        tblSolution.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {},
                        {},
                        {},
                        {}
                },
                new String[]{

                }
        ));
        jScrollPane1.setViewportView(tblSolution);

        btnBack.setText("Zurueck");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(16)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 382, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(52, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(338, Short.MAX_VALUE)
        			.addComponent(btnBack, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
        			.addGap(24))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 236, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(btnBack)
        			.addContainerGap(17, Short.MAX_VALUE))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        parentFrame.openSolutionsListGUI();

    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSolution;

    public void setTable(Solution solution) {
        DefaultTableModel tableModel = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        String titles[] = {"Runde", "Schiff", "Ressource", "Max. Kap.", "Freie Kap."};
        tableModel.setColumnIdentifiers(titles);

        List<Turn> turnList = new ArrayList<>(solution.getTurns());
        for (int i = 0; i < solution.getTurnCount(); i++) {
            List<Trip> tripList = new ArrayList<>(turnList.get(i).getTrips());
            for (Trip trip : tripList) {
                Object[] object = {(i+1), trip.getShip().getName(), trip.getResource(), trip.getShip().getCapacity(), (trip.getShip().getCapacity() - trip.getAmount())};
                tableModel.addRow(object);
            }
        }

        tblSolution.setModel(tableModel);
    }
    // End of variables declaration//GEN-END:variables
    
    public void clearView() {
    	DefaultTableModel model = (DefaultTableModel) tblSolution.getModel();
		model.setRowCount(0);
		
		setVisible(false);
    }
}
