/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project.GUI;

import project.Solution;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;

/**
 *
 * @author fcastillo
 */
public class SolutionsListGui extends javax.swing.JPanel {

    private ToolGUI parentFrame;
    private List<Solution> solutions;
    /**
     * Creates new form SolutionGui
     */
    public SolutionsListGui(ToolGUI parentFrame) {
        initComponents();
        this.parentFrame = parentFrame;
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSolutions = new javax.swing.JTable();
        btnOpen = new javax.swing.JButton();
        btnOpen.setFont(new Font("Tahoma", Font.BOLD, 14));
        jLabel1 = new javax.swing.JLabel();

        tblSolutions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblSolutions);
        tblSolutions.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                btnOpen.setEnabled(tblSolutions.getSelectedRow() > - 1);
            }
        });

        btnOpen.setText("Oeffnen");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Loesungen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(38, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel1)
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 373, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnOpen, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addGap(7)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 205, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(btnOpen)
        			.addContainerGap(16, Short.MAX_VALUE))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        int indexSolution = (int) tblSolutions.getValueAt(tblSolutions.getSelectedRow(),0);
        parentFrame.openSolutionGUIAndShowSelectedSolution(indexSolution - 1);
    }//GEN-LAST:event_btnOpenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSolutions;
    // End of variables declaration//GEN-END:variables

    public void setTitleTable() {
        DefaultTableModel tableModel = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        String titles[] = {"Nr.", "Runden", "Freie Kapazitaet"};
        tableModel.setColumnIdentifiers(titles);
        tblSolutions.setModel(tableModel);

        btnOpen.setEnabled(false);
    }

    public void updateTable(List<Solution> solutions) {
        DefaultTableModel dtm = (DefaultTableModel) tblSolutions.getModel();          
        
        dtm.setRowCount(0);

        if (solutions == null)
        	return;
        if(solutions.isEmpty())
            return;
        this.solutions = solutions;
        for(int i = 0; i < solutions.size(); i++){
            Object[]  object = {(i+1),solutions.get(i).getTurnCount(), solutions.get(i).getFreeCapacity()};
            ((DefaultTableModel)tblSolutions.getModel()).addRow(object);
        }
        
        
    }

    public List<Solution> getSolutions() {
        return solutions;
    }
    
    public void clearView() {
    	updateTable(null);
    	setVisible(false);    	
    }
}
